version: "3.7"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    ports:
        - "80:80/tcp"
        - "53:53/tcp"
        - "53:53/udp"
    environment:
        DNS1: '10.0.0.2#5054'
        DNS2: ''
        IPv6: 'false'
        TZ: 'Australia/Melbourne'
        DNSSEC: 'True'
        DNSMASQ_LISTENING: 'all'
        WEBPASSWORD: 'admin'
        PIHOLELOG: '/dev/null'
    volumes:
        - './etc-pihole/:/etc/pihole/'
        - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
