version: "3.7"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared
    restart: unless-stopped
    network_mode: host

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    network_mode: host
    environment:
        DNS1: '127.0.0.1#5054'
        DNS2: ''
        IPv6: 'false'
        TZ: 'Australia/Melbourne'
        DNSSEC: 'True'
        DNSMASQ_LISTENING: 'all'
        WEBPASSWORD: 'admin'
        PIHOLELOG: '/dev/null'
    volumes:
        - './etc-pihole/:/etc/pihole/'
        - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN

